USE Nexus;

GO

DROP TABLE IF EXISTS InACategory;

DROP TABLE IF EXISTS InAnOrganization;

DROP TABLE IF EXISTS OrganizationOwns;

DROP TABLE IF EXISTS Organization;

DROP TABLE IF EXISTS Category;

DROP TABLE IF EXISTS UserOwns;

DROP TABLE IF EXISTS UserLikes;

DROP TABLE IF EXISTS UserViewed;

DROP TABLE IF EXISTS Document;

DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS RegionLabel;