CREATE DATABASE Nexus
ON PRIMARY 
(NAME = 'Nexus', 
 FILENAME = 'D:\Database\MSSQL15.MSSQLSERVER\MSSQL\DATA\Nexus.mdf', 
 SIZE = 600MB, 
 MAXSIZE = 3000MB, 
 FILEGROWTH = 12%) 
LOG ON 
(NAME = 'Nexus_log', 
 FILENAME = 'D:\Database\MSSQL15.MSSQLSERVER\MSSQL\DATA\Nexus_log.ldf', 
 SIZE = 300MB, 
 MAXSIZE = 2200MB, 
 FILEGROWTH = 17%);