USE NexusTmp
GO

DROP TABLE IF EXISTS InACategory
DROP TABLE IF EXISTS InAnOrganization
DROP TABLE IF EXISTS OrganizationOwns
DROP TABLE IF EXISTS Organization
DROP TABLE IF EXISTS UserCreated
DROP TABLE IF EXISTS Category
DROP TABLE IF EXISTS UserInputtedData
DROP TABLE IF EXISTS UserOwns
DROP TABLE IF EXISTS Document
DROP TABLE IF EXISTS Users
