USE Nexus
GO

CREATE TABLE Users (
	UserName VARCHAR(30) PRIMARY KEY NOT NULL,
	MiddleName VARCHAR(30),
	LastName VARCHAR(50) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	FirebaseToken VARCHAR(30) NOT NULL
);