USE Nexus
GO

CREATE TABLE UserOwns (
	UserName VARCHAR(20) NOT NULL,
	DocumentID INT NOT NULL,
	FOREIGN KEY (UserName) REFERENCES Users(UserName) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (DocumentID) REFERENCES Document(DocumentID) ON DELETE CASCADE ON UPDATE CASCADE
);